package VIEW;

/**
 *
 * @author MASB
 */
import Controller.validateInput;
import Controller.LoginController;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class LOGIN extends javax.swing.JFrame {

    /**
     * Creates new form LOGIN
     */
    public LOGIN() {
        initComponents(); 
        this.setLocationRelativeTo(null); 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SALIDAA = new javax.swing.JButton();
        LOGO = new javax.swing.JLabel();
        DIENTE = new javax.swing.JLabel();
        USUARIO = new javax.swing.JLabel();
        CONTRASEÑA = new javax.swing.JLabel();
        JUSUARIO = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnIniciar = new javax.swing.JButton();
        FONDO1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SALIDAA.setBackground(new java.awt.Color(226, 226, 226));
        SALIDAA.setText("Salir");
        SALIDAA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SALIDAAActionPerformed(evt);
            }
        });
        getContentPane().add(SALIDAA, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, 20));

        LOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/LOGO_1.jpeg"))); // NOI18N
        getContentPane().add(LOGO, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, 220, 130));

        DIENTE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/Imagen1.png"))); // NOI18N
        getContentPane().add(DIENTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));

        USUARIO.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        USUARIO.setForeground(new java.awt.Color(255, 255, 255));
        USUARIO.setText("USUARIO :");
        getContentPane().add(USUARIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        CONTRASEÑA.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        CONTRASEÑA.setForeground(new java.awt.Color(255, 255, 255));
        CONTRASEÑA.setText("CONTRASEÑA :");
        getContentPane().add(CONTRASEÑA, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, -1, -1));

        JUSUARIO.setBackground(new java.awt.Color(238, 208, 230));
        JUSUARIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JUSUARIOActionPerformed(evt);
            }
        });
        getContentPane().add(JUSUARIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 220, 30));

        txtPassword.setBackground(new java.awt.Color(238, 208, 230));
        getContentPane().add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 220, 30));

        btnIniciar.setBackground(new java.awt.Color(226, 226, 226));
        btnIniciar.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnIniciar.setText("Iniciar ");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 370, -1, 20));

        FONDO1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/fondo-abstracto-poligonal-geometrico-origami-estilo-3d_107146-98.jpg"))); // NOI18N
        FONDO1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(FONDO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SALIDAAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SALIDAAActionPerformed
       System.exit(0);
    }//GEN-LAST:event_SALIDAAActionPerformed

    private void JUSUARIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JUSUARIOActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JUSUARIOActionPerformed

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        
        if(validateInput.validarExistenciaCampos(JUSUARIO) && validateInput.validarExistenciaCampos(txtPassword)){
            System.out.println("Iniciando Sesión :D");
            try {
                if(LoginController.login(JUSUARIO.getText(), txtPassword.getText())){
                    //Cambiar Esto
                    Menu menu = new Menu();
                    menu.setVisible(true);
                    this.dispose();
                }else{
                    JOptionPane.showMessageDialog(null, "¡La combinación que proporcionas no es correcta!", "¡Alerta!", JOptionPane.ERROR_MESSAGE);
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(LOGIN.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            txtPassword.setText("");
            JUSUARIO.setText("");
            JOptionPane.showMessageDialog(null, "Revisa tus campos, no han sido llenados correctamente", "¡Alerta!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnIniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CONTRASEÑA;
    private javax.swing.JLabel DIENTE;
    private javax.swing.JLabel FONDO1;
    private javax.swing.JTextField JUSUARIO;
    private javax.swing.JLabel LOGO;
    private javax.swing.JButton SALIDAA;
    private javax.swing.JLabel USUARIO;
    private javax.swing.JButton btnIniciar;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
